import React from 'react';
import ReactMarkdown from 'react-markdown';

// Styles simulating WeChat Official Account
const styles = {
    h2: "border-l-4 border-[#07c160] pl-3 text-lg font-bold text-gray-900 mb-6 mt-8 py-1",
    p: "text-[16px] text-[#333] leading-[1.8] mb-6 tracking-wide text-justify font-sans",
    li: "text-[#333] leading-7 mb-2 list-disc ml-4",
    strong: "font-bold text-[#07c160]",
};

interface RendererProps {
    content: string;
    images?: string[];
}

export const WeChatRenderer: React.FC<RendererProps> = ({ content, images }) => {
    return (
        <div className="relative w-[375px] h-[750px] bg-black rounded-[45px] shadow-2xl border-[8px] border-gray-900 overflow-hidden ring-4 ring-gray-200/20">

            {/* Notch & Status Bar */}
            <div className="absolute top-0 w-full h-12 bg-gray-50 z-20 flex justify-between items-end px-6 pb-2">
                <span className="text-xs font-semibold text-black">9:41</span>
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-32 h-7 bg-black rounded-b-2xl"></div>
                <div className="flex gap-1.5">
                    <div className="w-4 h-2.5 bg-black rounded-[1px]"></div>
                    <div className="w-4 h-2.5 bg-black rounded-[1px]"></div>
                </div>
            </div>

            {/* WeChat Header */}
            <div className="absolute top-12 w-full h-12 bg-[#ededed] border-b border-gray-300/50 flex items-center justify-between px-4 z-10 text-black">
                <div className="text-lg font-medium">WeCreate AI</div>
                <div className="w-8 h-8 rounded-full border border-gray-400 flex items-center justify-center">•••</div>
            </div>

            {/* Scrollable Content Area */}
            <div className="w-full h-full pt-24 pb-12 bg-white overflow-y-auto no-scrollbar scroll-smooth">
                <div className="px-5 py-4 min-h-[1000px]">
                    {/* Title Block */}
                    <h1 className="text-2xl font-bold mb-3 text-black">AI 生成文章预览</h1>
                    <div className="flex items-center gap-2 mb-8 text-sm text-[rgba(0,0,0,0.3)]">
                        <span className="text-[#576b95] font-medium">WeCreate</span>
                        <span>2024-01-20</span>
                    </div>

                    {/* Content */}
                    <div className="prose prose-p:my-4 prose-headings:font-bold max-w-none">
                        <ReactMarkdown
                            components={{
                                h2: ({ node, ...props }) => <h2 className={styles.h2} {...props} />,
                                p: ({ node, ...props }) => <p className={styles.p} {...props} />,
                                li: ({ node, ...props }) => <li className={styles.li} {...props} />,
                                strong: ({ node, ...props }) => <strong className={styles.strong} {...props} />,
                            }}
                        >
                            {content}
                        </ReactMarkdown>
                    </div>

                    {/* Images */}
                    {images && images.map((img, i) => (
                        <div key={i} className="my-8 rounded-lg overflow-hidden shadow-sm">
                            <img src={img} className="w-full h-auto object-cover" />
                            <div className="p-3 bg-gray-50 text-center text-xs text-gray-500 flex items-center justify-center gap-1">
                                <span className="w-3 h-3 rounded-full bg-green-500/20 flex items-center justify-center text-green-600">AI</span>
                                Generated by DALL-E 3
                            </div>
                        </div>
                    ))}

                    <div className="mt-16 text-center text-xs text-gray-300">
                        预览结束
                    </div>
                </div>
            </div>

            {/* Home Indicator */}
            <div className="absolute bottom-1 left-1/2 -translate-x-1/2 w-32 h-1 bg-black rounded-full z-20"></div>
        </div>
    );
};
